# Базовая часть

## Задание 1.1

Напишите функцию, которая принимает список чисел my_list (количество товаров разных марок) и число $n$ и возвращает сумму всех чисел списка меньше либо равных $n$ (суммарное количество товаров, которых в наличие меньше либо равно $n$).

In [6]:
import numpy as np
def function_1_1(my_list, n):
    b=np.array([])
    for i in my_list:
        if i<=n:
            b=np.append(b,i)
    return int(np.sum(b))

In [7]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 7) ==31

True

In [8]:
function_1_1([1, 2, 3, 4, 4, 3, 2, 1], 7) == 20

True

In [9]:
function_1_1([1, 2, 3, 4, 4, 3, 2, 1], 3) == 12

True

In [10]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 5) == 18

True

In [11]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 3) == 9

True

In [12]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 0) == 0

True

#### Значение для формы

In [13]:
import random

random.seed(42)
print(function_1_1([random.randint(0, 1000) for _ in range(10000)], 700))

2496584


## Задание 1.2

Имеется список пар (фамилия, долг) $my\_list$ и число $dept$. Нужно написать функцию, которая для каждой фамилии находит суммарный долг и выводит отсортированный список фамилий, у которых долг строго больше $dept$.

Одна и та же фамилия может встречаться несколько раз, и тогда долги по ней суммируются.

In [84]:
import numpy as np

def function_1_2(my_list, dept):
    data = [my_list[i][1] for i in range(len(my_list)) ]
    groups = [my_list[i][0] for i in range(len(my_list)) ]
    x, y = np.meshgrid(groups, np.unique(groups))
    data_stack = np.tile(data, (np.unique(groups).size, 1))

    data_in_group = np.zeros_like(data_stack)
    data_in_group[x==y] = data_stack[x==y]

    sums = data_in_group.sum(axis=1)


    return np.unique(groups)[sums > dept].tolist()

In [93]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 1)==['Ivanov', 'Petrov', 'Sidorov']

True

In [94]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 2) == ['Ivanov', 'Sidorov']

True

In [95]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 3) == ['Sidorov']

True

In [96]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 4) == []

True

In [97]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 1), ('Sidorov', 4)], 2) == ['Sidorov']

True

In [98]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 2) == ['Ivanov', 'Petrov']

True

In [99]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 3) == ['Petrov']

True

#### Значение для формы

In [100]:
import random
import numpy as np


random.seed(42)
print(','.join(function_1_2([
    (str(random.randint(1, 20)), random.randint(1, 1000) )
    for _ in range(1000)
], 25000)))

10,11,14,18,19,3,4,5,8,9


# Продвинутая часть

## Задание 2.1

Напишите функцию, принимающую число $n$ и считающую $n!$, не используя модуль math

$n! = 1 \cdot 2 \cdot 3 \cdot \dots \cdot (n - 1) \cdot n$

Подсказка: воспользуйтесь циклами

In [157]:
def function_2_1(n):
    if n == 0:
        return 1
    else:
        return n * function_2_1(n-1)

In [158]:
function_2_1(3) == 6

True

In [159]:
function_2_1(5) == 120

True

In [160]:
function_2_1(9) == 362880

True

In [161]:
function_2_1(13) == 6227020800

True

#### Значение для формы

In [162]:
print(function_2_1(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


## Задание 2.2

Есть два списка чисел: цены товаров в одном магазине и цены товаров в другом магазине.

Нужно сравнить средние (среднее берётся по всем товарам) цены, минимальные цены и максимальные  в магазинах. Если первое зачение меньше надо вернуть 'First', если второе, то 'Second', а если равны, то 'Equal'

Например, function_2_2([1, 2, 3], [2, 2, 2])

В первом магазине среднее значение 2, минимальное 1, максимальное 3. А во втором среднее 2, минимальное 2 и максимальное 2.

Результаты сравнения $2 = 2,~1 < 2,~3 > 2$, поэтому нужно вернуть  ('Equal', 'First', 'Second')

In [142]:
def function_2_2(list1, list2):
    b=np.array([])
    mn1=min(list1)
    mn2=min(list2)
    mx1=max(list1)
    mx2=max(list2)
    mean1=sum(list1)/len(list1)
    mean2=sum(list2)/len(list2)
    if mean1==mean2:
        b=np.append(b, 'Equal')
    elif mean1>mean2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')
    if mn1==mn2:
        b=np.append(b, 'Equal')
    elif mn1>mn2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')
    if mx1==mx2:
        b=np.append(b, 'Equal')
    elif mx1>mx2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')

    return b


In [151]:
function_2_2([1, 2, 3], [2, 2, 2])==('Equal', 'First', 'Second')

array([ True,  True,  True])

In [152]:
function_2_2([2, 2, 1], [4])==('First', 'First', 'First')

array([ True,  True,  True])

In [153]:
function_2_2([3, 5], [2, 4, 6]) == ('Equal', 'Second', 'First')

array([ True,  True,  True])

In [154]:
function_2_2([1, 7], [2, 4, 7]) == ('First', 'First', 'Equal')

array([ True,  True,  True])

#### Значение для формы

In [156]:
import random

random.seed(47)
print(','.join(function_2_2(
    [random.randint(0, 100000) for _ in range(1000)],
    [random.randint(0, 100000) for _ in range(1000)]
)))

Second,First,Second


# Сложная часть

## Задание 3.1

Вам известны количество продаж разных товаров. Они представлены в виде списка, первое значение - число продаж первого товара, второе значение - второго, и так далее. Вы хотите посмотреть на список самых популярных товаров среди тех, у которых объём продаж не выше заданного числа.

Напишите функцию, которая принимает список чисел my_list, число  $n$ и число $k$  и возвращает сумму $k$ наибольших чисел среди всех чисел списка меньше либо равных  $n$ .

In [166]:
from heapq import nlargest
def function_3_1(my_list, n, k):
    b=np.array([])
    for i in my_list:
        if i<=n:
            b=np.append(b,i)
    return sum(nlargest(k,b))

In [168]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 1)==7

True

In [169]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 3) == 18

True

In [170]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 5) == 25

True

In [171]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 8) == 31

True

In [172]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 10) == 31

True

In [173]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 6, 3) == 18

True

In [174]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 5, 3) == 13

True

In [175]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 4, 3) == 7

True

In [176]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 6, 2) == 12

True

In [177]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 5, 2) == 10

True

In [178]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 4, 2) == 6

True

#### Значение для формы

In [179]:
import random

random.seed(42)
print(function_3_1([random.randint(0, 1000) for _ in range(10000)], 700, 300))

205778.0


## Задание 3.2

Напишите списковое выражение, генерирующее все простые числа не больше заданного числа

In [186]:
def isPrime(n): 
    
    if n <= 1 : 
        return False

    # check from 2 to n-1 
    for i in range(2, n): 
        if n % i == 0: 
            return False

    return True

# Function that prints primes 
def function_3_2(n): 
    b=np.array([])
    for i in range(2, n + 1): 
        if isPrime(i): 
            b=np.append(b,i)
    return b
function_3_2(3)




array([2., 3.])

In [187]:
function_3_2(3) == [2, 3]

array([ True,  True])

In [188]:
function_3_2(10) == [2, 3, 5, 7]

array([ True,  True,  True,  True])

In [189]:
function_3_2(20) == [2, 3, 5, 7, 11, 13, 17, 19]

array([ True,  True,  True,  True,  True,  True,  True,  True])

#### Значение для формы

In [190]:
print(sum(function_3_2(10000)))

5736396.0


# По хардкору

## Задание 4.1

Напишите функцию, которая по множеству, возвращает список всех его подмножеств

In [2]:
from itertools import chain, combinations
def function_4_1(my_set):
    
    "list(powerset([1,2,3])) --> [(), (1,), (2,), (3,), (1,2), (1,3), (2,3), (1,2,3)]"
    s = list(my_set)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

#### Значение для формы

In [3]:
print(sum([
    len(subset) - sum(subset) + sum(subset) ** 2
    for subset in function_4_1(set(range(2, 21, 3)))
]))

220416
