# Базовая часть

## Задание 1.1

Напишите функцию, которая принимает список чисел my_list (количество товаров разных марок) и число $n$ и возвращает сумму всех чисел списка меньше либо равных $n$ (суммарное количество товаров, которых в наличие меньше либо равно $n$).

In [1]:
import numpy as np
def function_1_1(my_list, n):
    b=np.array([])
    for i in my_list:
        if i<=n:
            b=np.append(b,i)
    return int(np.sum(b))

In [2]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 7) ==31

True

In [3]:
function_1_1([1, 2, 3, 4, 4, 3, 2, 1], 7) == 20

True

In [4]:
function_1_1([1, 2, 3, 4, 4, 3, 2, 1], 3) == 12

True

In [5]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 5) == 18

True

In [6]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 3) == 9

True

In [7]:
function_1_1([1, 2, 3, 4, 5, 6, 3, 7], 0) == 0

True

#### Значение для формы

In [8]:
import random

random.seed(42)
print(function_1_1([random.randint(0, 1000) for _ in range(10000)], 700))

2496584


## Задание 1.2

Имеется список пар (фамилия, долг) $my\_list$ и число $dept$. Нужно написать функцию, которая для каждой фамилии находит суммарный долг и выводит отсортированный список фамилий, у которых долг строго больше $dept$.

Одна и та же фамилия может встречаться несколько раз, и тогда долги по ней суммируются.

In [9]:
import numpy as np

def function_1_2(my_list, dept):
    data = [my_list[i][1] for i in range(len(my_list)) ]
    groups = [my_list[i][0] for i in range(len(my_list)) ]
    x, y = np.meshgrid(groups, np.unique(groups))
    data_stack = np.tile(data, (np.unique(groups).size, 1))

    data_in_group = np.zeros_like(data_stack)
    data_in_group[x==y] = data_stack[x==y]

    sums = data_in_group.sum(axis=1)


    return np.unique(groups)[sums > dept].tolist()

In [10]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 1)==['Ivanov', 'Petrov', 'Sidorov']

True

In [11]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 2) == ['Ivanov', 'Sidorov']

True

In [12]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 3) == ['Sidorov']

True

In [13]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 4) == []

True

In [14]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 1), ('Sidorov', 4)], 2) == ['Sidorov']

True

In [15]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 2) == ['Ivanov', 'Petrov']

True

In [16]:
function_1_2([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 3) == ['Petrov']

True

#### Значение для формы

In [17]:
import random
import numpy as np


random.seed(42)
print(','.join(function_1_2([
    (str(random.randint(1, 20)), random.randint(1, 1000) )
    for _ in range(1000)
], 25000)))

10,11,14,18,19,3,4,5,8,9


# Продвинутая часть

## Задание 2.1

Напишите функцию, принимающую число $n$ и считающую $n!$, не используя модуль math

$n! = 1 \cdot 2 \cdot 3 \cdot \dots \cdot (n - 1) \cdot n$

Подсказка: воспользуйтесь циклами

In [18]:
def function_2_1(n):
    if n == 0:
        return 1
    else:
        return n * function_2_1(n-1)

In [19]:
function_2_1(3) == 6

True

In [20]:
function_2_1(5) == 120

True

In [21]:
function_2_1(9) == 362880

True

In [22]:
function_2_1(13) == 6227020800

True

#### Значение для формы

In [23]:
print(function_2_1(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


## Задание 2.2

Есть два списка чисел: цены товаров в одном магазине и цены товаров в другом магазине.

Нужно сравнить средние (среднее берётся по всем товарам) цены, минимальные цены и максимальные  в магазинах. Если первое зачение меньше надо вернуть 'First', если второе, то 'Second', а если равны, то 'Equal'

Например, function_2_2([1, 2, 3], [2, 2, 2])

В первом магазине среднее значение 2, минимальное 1, максимальное 3. А во втором среднее 2, минимальное 2 и максимальное 2.

Результаты сравнения $2 = 2,~1 < 2,~3 > 2$, поэтому нужно вернуть  ('Equal', 'First', 'Second')

In [24]:
def function_2_2(list1, list2):
    b=np.array([])
    mn1=min(list1)
    mn2=min(list2)
    mx1=max(list1)
    mx2=max(list2)
    mean1=sum(list1)/len(list1)
    mean2=sum(list2)/len(list2)
    if mean1==mean2:
        b=np.append(b, 'Equal')
    elif mean1>mean2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')
    if mn1==mn2:
        b=np.append(b, 'Equal')
    elif mn1>mn2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')
    if mx1==mx2:
        b=np.append(b, 'Equal')
    elif mx1>mx2:
        b=np.append(b, 'Second')
    else:
        b=np.append(b, 'First')

    return b


In [25]:
function_2_2([1, 2, 3], [2, 2, 2])==('Equal', 'First', 'Second')

array([ True,  True,  True])

In [26]:
function_2_2([2, 2, 1], [4])==('First', 'First', 'First')

array([ True,  True,  True])

In [27]:
function_2_2([3, 5], [2, 4, 6]) == ('Equal', 'Second', 'First')

array([ True,  True,  True])

In [28]:
function_2_2([1, 7], [2, 4, 7]) == ('First', 'First', 'Equal')

array([ True,  True,  True])

#### Значение для формы

In [29]:
import random

random.seed(47)
print(','.join(function_2_2(
    [random.randint(0, 100000) for _ in range(1000)],
    [random.randint(0, 100000) for _ in range(1000)]
)))

Second,First,Second


# Сложная часть

## Задание 3.1

Вам известны количество продаж разных товаров. Они представлены в виде списка, первое значение - число продаж первого товара, второе значение - второго, и так далее. Вы хотите посмотреть на список самых популярных товаров среди тех, у которых объём продаж не выше заданного числа.

Напишите функцию, которая принимает список чисел my_list, число  $n$ и число $k$  и возвращает сумму $k$ наибольших чисел среди всех чисел списка меньше либо равных  $n$ .

In [30]:
from heapq import nlargest
def function_3_1(my_list, n, k):
    b=np.array([])
    for i in my_list:
        if i<=n:
            b=np.append(b,i)
    return sum(nlargest(k,b))

In [31]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 1)==7

True

In [32]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 3) == 18

True

In [33]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 5) == 25

True

In [34]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 8) == 31

True

In [35]:
function_3_1([1, 2, 3, 4, 5, 6, 3, 7], 7, 10) == 31

True

In [36]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 6, 3) == 18

True

In [37]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 5, 3) == 13

True

In [38]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 4, 3) == 7

True

In [39]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 6, 2) == 12

True

In [40]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 5, 2) == 10

True

In [41]:
function_3_1([1, 5, 3, 6, 5, 6, 3, 6], 4, 2) == 6

True

#### Значение для формы

In [42]:
import random

random.seed(42)
print(function_3_1([random.randint(0, 1000) for _ in range(10000)], 700, 300))

205778.0


## Задание 3.2

Напишите списковое выражение, генерирующее все простые числа не больше заданного числа

In [43]:
def isPrime(n): 
    
    if n <= 1 : 
        return False

    # check from 2 to n-1 
    for i in range(2, n): 
        if n % i == 0: 
            return False

    return True

# Function that prints primes 
def function_3_2(n): 
    b=np.array([])
    for i in range(2, n + 1): 
        if isPrime(i): 
            b=np.append(b,i)
    return b
function_3_2(3)




array([2., 3.])

In [44]:
function_3_2(3) == [2, 3]

array([ True,  True])

In [45]:
function_3_2(10) == [2, 3, 5, 7]

array([ True,  True,  True,  True])

In [46]:
function_3_2(20) == [2, 3, 5, 7, 11, 13, 17, 19]

array([ True,  True,  True,  True,  True,  True,  True,  True])

#### Значение для формы

In [47]:
print(sum(function_3_2(10000)))

5736396.0


# По хардкору

## Задание 4.1

Напишите функцию, которая по множеству, возвращает список всех его подмножеств

In [64]:
from itertools import chain, combinations
def function_4_1(my_set):
    
    "list(powerset([1,2,3])) --> [(), (1,), (2,), (3,), (1,2), (1,3), (2,3), (1,2,3)]"
    s = list(my_set)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [65]:
def check_4_1(my_set, function_res):
    if len(function_res) != len(set(map(frozenset, function_res))):
        return False
    if len(function_res) != 2 ** len(my_set):
        return False
    return all(x <= my_set for x in function_res)
list(function_4_1(set(range(10))))

[(),
 (0,),
 (1,),
 (2,),
 (3,),
 (4,),
 (5,),
 (6,),
 (7,),
 (8,),
 (9,),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 8),
 (7, 9),
 (8, 9),
 (0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 1, 5),
 (0, 1, 6),
 (0, 1, 7),
 (0, 1, 8),
 (0, 1, 9),
 (0, 2, 3),
 (0, 2, 4),
 (0, 2, 5),
 (0, 2, 6),
 (0, 2, 7),
 (0, 2, 8),
 (0, 2, 9),
 (0, 3, 4),
 (0, 3, 5),
 (0, 3, 6),
 (0, 3, 7),
 (0, 3, 8),
 (0, 3, 9),
 (0, 4, 5),
 (0, 4, 6),
 (0, 4, 7),
 (0, 4, 8),
 (0, 4, 9),
 (0, 5, 6),
 (0, 5, 7),
 (0, 5, 8),
 (0, 5, 9),
 (0, 6, 7),
 (0, 6, 8),
 (0, 6, 9),
 (0, 7, 8),
 (0, 7, 9),
 (0, 8, 9),
 (1, 2, 3),
 (1, 2, 4),
 (1, 2, 5),
 (1, 2, 6),
 (1, 2, 7),
 (1, 2, 8),
 (1, 2, 9),
 (1,

#### Значение для формы

In [69]:
print(sum([
    len(subset) - sum(subset) + sum(subset) ** 2
    for subset in function_4_1(set(range(2, 21, 3)))
]))

220416


## Задание 4.2

Напишите функцию раскладывающее число на простые множители

по числу $n$ нужно вернуть список пар $(p_i, c_i)$ такой, что $\prod_i~p_i^{c_i} = n$

In [58]:
def  is_primeis_prime(n):
    return n > 1 and all(n % i != 0 for i in range(2, n))

def function_4_2(n):
    origin = n 
    factors = []
    for i in range(2,n+1):
        while np.prod(factors) != origin: 
            if is_prime(i)==True:                
                while n % i == 0 :
                    n = n / i
                    factors.append(i)
                i += 1
            else:
                break
    
    return [[x,factors.count(x)] for x in set(factors)]

In [59]:
def check_4_2(n, my_list):
    prod = 1
    for p, c in my_list:
        if not is_prime(p):
            return False
        prod *= p ** c
    return prod == n

In [60]:
check_4_2(10, function_4_2(10))

True

In [61]:
check_4_2(11690, function_4_2(11690))

True

In [62]:
check_4_2(254242, function_4_2(254242))

True

#### Значение для формы

In [63]:
print(sum(
    (c + 1) ** (p - 1) * c - p
    for p, c in function_4_2(7648)
))

441711766194596082395824375185729628956870974218904739530401550323154733
